name: extension_type_unions
description: Simple union types, expressed using extension types.
version: 1.0.0
# repository: https://github.com/eernstg/extension_type_unions

environment:
  sdk: '^3.2.0-edge' # '^3.1.0-333.0.dev'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
