name: inline_union_type
description: Simple union types, expressed using inline classes.
version: 1.0.0
# repository: https://github.com/eernstg/inline_union_type

environment:
  sdk: '>=3.1.0-40.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
