name: extension_type_unions
description: >-
  Simple union types using extension types. Types: the union of
  `int` and `String` is `Union2<int, String>`. Values: `42.u21` is
  `42` with type `Union2<int, Never>`.
version: 1.0.3
repository: https://github.com/eernstg/extension_type_unions

environment:
  sdk: '>=3.3.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
